name: focused-empathy
channels:
  - defaults
dependencies:
  - cudatoolkit=10.2
  - pytorch::pytorch=1.6.0
  - python=3.7.9
  - pip=20.2.3
  - pip:
    # December 3rd, 2020
    - git+https://github.com/facebookresearch/ParlAI.git@db7086c7b6fad98a2e4c5ef2423f805359661cd2
    - transformers==3.3.1
    - fairseq==0.9.0
    - pytorch-pretrained-bert==0.6.2
    - torchtext==0.7.0
    - spacy==2.3.2
    - rake-nltk
    # For logging
    - tqdm
    - better-exceptions
    - colorlog
    - colorful
    # For linting
    - pylint
    - pycodestyle
    - mypy
    # For markdown preview
    - grip
    # etc
    - ruamel.yaml
    - more_itertools
    - isort
    - pudb
    - jupyter
